services:
  postgres:
    image: postgres:15
    container_name: homelab-postgres
    environment:
      POSTGRES_DB: sklep_backup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - homelab

  n8n:
    image: n8nio/n8n:latest
    container_name: homelab-n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_workflows
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - homelab

  grafana:
    image: grafana/grafana:latest
    container_name: homelab-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - homelab

  node-exporter:
    image: prom/node-exporter:latest
    container_name: homelab-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - homelab

  prometheus:
    image: prom/prometheus:latest
    container_name: homelab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - homelab

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: homelab-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    ports:
      - "3001:80"
    volumes:
      - heimdall_data:/config
    restart: unless-stopped
    networks:
      - homelab

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: homelab-uptime-kuma
    ports:
      - "3002:3001"
    volumes:
      - uptime_data:/app/data
    restart: unless-stopped
    networks:
      - homelab

  linkding:
    image: sissbruecker/linkding:latest
    container_name: homelab-linkding
    ports:
      - "3003:9090"
    volumes:
      - linkding_data:/etc/linkding/data
    environment:
      - LD_SUPERUSER_NAME=admin
      - LD_SUPERUSER_PASSWORD=admin123
    restart: unless-stopped
    networks:
      - homelab

  it-tools:
    image: corentinth/it-tools:latest
    container_name: homelab-it-tools
    ports:
      - "3004:80"
    restart: unless-stopped
    networks:
      - homelab

  pihole:
    image: pihole/pihole:latest
    container_name: homelab-pihole
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      SERVERIP: '192.168.1.13'
      DNS1: '1.1.1.1'
      DNS2: '8.8.8.8'
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN

  wireguard:
    image: linuxserver/wireguard
    container_name: homelab-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
      SERVERURL: auto
      SERVERPORT: 51820
      PEERS: 3
      PEERDNS: homelab-pihole  # Use container name instead of IP
      INTERNAL_SUBNET: 10.13.13.0
    volumes:
      - wireguard_config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - homelab
    depends_on:
      - pihole

networks:
  homelab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  n8n_data:
  grafana_data:
  prometheus_data:
  uptime_data:
  linkding_data:
  heimdall_data:
  pihole_etc:
  pihole_dnsmasq:
  wireguard_config:
