- Quick Business:
    - VPS Server: "ssh://194.59.140.170"
    - GitHub Repo: "https://github.com/persmati/homelab"
    - Facebook Business: "https://business.facebook.com"
    - Google Analytics: "https://analytics.google.com"

- Development:
    - GitHub: "https://github.com/persmati"
    - Stack Overflow: "https://stackoverflow.com"
    - Docker Hub: "https://hub.docker.com"
    - Grafana Docs: "https://grafana.com/docs"

- Daily Tools:
    - Gmail: "https://gmail.com"
    - Google Calendar: "https://calendar.google.com"
    - Google Drive: "https://drive.google.com"
    - YouTube: "https://youtube.com"

- Learning:
    - Kubernetes Docs: "https://kubernetes.io/docs"
    - Docker Docs: "https://docs.docker.com"
    - PostgreSQL Docs: "https://postgresql.org/docs"
    - n8n Community: "https://community.n8n.io"
